language: perl
perl:
   - 'blead'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
   - '5.8'
env:
   - BUILD=0
   - BUILD=1
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - rm .travis.yml
   - export AUTHOR_TESTING=0
   - git checkout $TRAVIS_BRANCH
   - git reset --hard $TRAVIS_COMMIT
install:
   - cpanm --installdeps --verbose  .
   - cpan-install --coverage
after_success:
   - coverage-report
