---
abstract: 'Calculate edit distance based on insertion, deletion, substitution, and transposition'
author:
  - 'ugexe <ugexe@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Levenshtein-XS
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Text::Levenshtein::XS:
    file: lib/Text/Levenshtein/XS.pm
    version: '0.47'
requires:
  Exporter: '0'
  XSLoader: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/ugexe/Text--Levenshtein--XS/issues
  homepage: https://github.com/ugexe/Text--Levenshtein--XS
  repository: https://github.com/ugexe/Text--Levenshtein--XS.git
version: '0.47'
x_authority: cpan:UGEXE
x_contributors:
  - 'Nick <nlogan@gmail.com>'
  - 'ugexe <nlogan@gmail.com>'
